[package]
name = "ircd2"
description = "P2P IRC daemon"
version = "0.4.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../", features = ["net", "rpc", "bs58"]}
darkfi-serial = {path = "../../src/serial"}

# Async
smol = "1.3.0"
futures = "0.3.25"
futures-rustls = "0.22.2"
rustls-pemfile = "1.0.1"
async-std = "1.12.0"
async-trait = "0.1.59"
easy-parallel = "3.2.0"

# Crypto
crypto_box = "0.8.2"
rand = "0.8.5"

# Misc
clap = {version = "4.0.29", features = ["derive"]}
log = "0.4.17"
simplelog = "0.12.0"
ctrlc = { version = "3.2.4", features = ["termination"] }
url = "2.3.1"
chrono = "0.4.23"
ripemd = "0.1.3"

# Encoding and parsing
serde_json = "1.0.89"
serde = {version = "1.0.150", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
bs58 = "0.4.0"
toml = "0.5.10"
hex = "0.4.3"
