# JSON-RPC listen URL
rpc_listen="127.0.0.1:8857"
# IRC listen URL
irc_listen="127.0.0.1:8855"
# Sets Datastore Path
datastore="~/.config/tau"

# Raft net settings
type="Net"
[args]
inbound="127.0.0.1:11002"
outbound_connections=0
manual_attempt_limit=0
seed_query_timeout_seconds=8
connect_timeout_seconds=10
channel_handshake_seconds=4
channel_heartbeat_seconds=10
external_addr="127.0.0.1:11002"
peers=["127.0.0.1:11003"]
seeds=["127.0.0.1:11001"]
