[package]
name = "clock_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
ntp = "0.5.0"
reqwest = "0.11.10"
serde_json = "1.0.81"
tokio = { version = "1.18.1", features = ["full"] }

[workspace]
