[package]
name = "lilith"
description = "Daemon that spawns P2P seeds"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../", features = ["net", "rpc"]}

# Async
async-std = "1.12.0"
async-trait = "0.1.68"
futures = "0.3.28"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.15"
easy-parallel = "3.3.0"
smol = "1.3.0"

# Misc
log = "0.4.19"
semver = "1.0.17"
serde_json = "1.0.96"
simplelog = "0.12.1"
url = "2.4.0"

# Argument parsing
serde = {version = "1.0.164", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
toml = "0.7.4"
