[package]
name = "lilith"
description = "Daemon that spawns P2P seeds"
version = "0.3.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../", features = ["net", "rpc"]}

# Async
async-std = "1.12.0"
async-trait = "0.1.58"
ctrlc = { version = "3.2.3", features = ["termination"] }
easy-parallel = "3.2.0"
smol = "1.2.5"

# Misc
fxhash = "0.2.1"
log = "0.4.17"
serde_json = "1.0.87"
simplelog = "0.12.0"
url = "2.3.1"

# Argument parsing
serde = {version = "1.0.147", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
toml = "0.5.9"
