## lilith configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# JSON-RPC listen URL
#rpc_listen = "tcp://127.0.0.1:18927"

# Daemon published urls, common for all enabled networks.
# These should be without a port.
accept_addrs = [
    "tcp://0.0.0.0",
    "tcp://[::]",
    "tcp+tls://0.0.0.0",
    "tcp+tls://[::]",
]

# Hosts .tsv file to use
#hosts_file="~/.config/darkfi/lilith_hosts.tsv"

## Per-network settings
#[network."darkfid_sync_v4"]
#port = 33032
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false

#[network."darkfid_consensus_v4"]
#port = 33033
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false

#[network."darkirc_v4"]
#port = 25551
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false

#[network."taud_v4"]
#port = 23331
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false
