[package]
name = "vanityaddr"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Vanity address generation tool for DarkFi keypairs."
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
clap = {version = "4.0.28", features = ["derive"]}
ctrlc = "3.2.3"
darkfi = {path = "../../", features = ["crypto"]}
darkfi-sdk = {path = "../../src/sdk"}
indicatif = "0.17.2"
num_cpus = "1.14.0"
rand = "0.8.5"
rayon = "1.6.0"
