[package]
name = "vanityaddr"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Vanity address generation tool for DarkFi keypairs and token IDs"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
clap = {version = "4.1.4", features = ["derive"]}
ctrlc = "3.2.4"
darkfi = {path = "../../"}
darkfi-sdk = {path = "../../src/sdk"}
indicatif = "0.17.3"
num_cpus = "1.15.0"
rand = "0.8.5"
rayon = "1.6.1"
