[package]
name = "vanityaddr"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = {version = "3.1.6", features = ["derive"]}
bs58 = "0.4.0"
num_cpus = "1.13.1"
rand = "0.8.5"
rayon = "1.5.1"
serde_json = "1.0.79"

[dependencies.darkfi]
path = "../../"
features = ["crypto", "util"]
