[package]
name = "tau"
description = "Command-line client for taud"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
chrono = "0.4.24"
clap = {version = "4.2.7", features = ["derive"]}
colored = "2.0.0"
darkfi = { path = "../../../", features = ["rpc"]}
log = "0.4.17"
prettytable-rs = "0.10.0"
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
simplelog = "0.12.1"
term_grid = { git = "https://github.com/Dastan-glitch/rust-term-grid.git" }
textwrap = "0.15.2"
url = "2.3.1"
