## cashierd configuration file
##
## Please make sure you go through all the settings so you can configre
## your daemon properly.

# The DNS name of the cashier (can also be an IP, or a .onion address)
dns_addr = "testnet.cashier.dark.fi"

# The endpoint where cashierd will bind its RPC socket
rpc_listen_address = "127.0.0.1:9000"

# Whether to listen with TLS or plain TCP
serve_tls = false

# Path to DER-formatted PKCS#12 archive. (Unused if serve_tls=false)
# This can be created using openssl:
# openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem -certfile chain_certs.pem
tls_identity_path = "~/.config/darkfi/cashierd_identity.pfx"

# Password for the created TLS identity. (Unused if serve_tls=false)
tls_identity_password = "FOOBAR"

# The endpoint to a gatewayd protocol API
gateway_protocol_url = "tcp://testnet.gateway-protocol.dark.fi:3333"

# The endpoint to a gatewayd publisher API
gateway_publisher_url = "tcp://testnet.gateway-publish.dark.fi:4444"

# Path to mint.params
mint_params_path = "/usr/local/share/darkfi/mint.params"

# Path to spend.params
spend_params_path = "/usr/local/share/darkfi/spend.params"

# Path to cashierd wallet
cashier_wallet_path = "~/.config/darkfi/cashier_wallet.db"

# Password for cashierd wallet
cashier_wallet_password = "TEST_PASSWORD"

# Path to client wallet
client_wallet_path = "~/.config/darkfi/cashier_client_wallet.db"

# Password for client wallet
client_wallet_password = "TEST_PASSWORD"

# Path to database
database_path = "~/.config/darkfi/cashier_database.db"

# The configured networks to use.
[[networks]]
name = "sol"
blockchain = "devnet"
# The path to a secret key (can be created with solana-keygen new --no-bip39-passphrase)
keypair = ""

[[networks]]
name = "btc"
blockchain = "testnet"
keypair = ""

[[networks]]
name = "eth"
blockchain = "ropsten"
keypair = ""
