## cashierd configuration file
##
## Please make sure you go through all the settings so you can configre
## your daemon properly.

# The endpoint where cashierd will bind its RPC socket
listen_url = "127.0.0.1:9000"

# Whether to listen with TLS or plain TCP
serve_tls = false

# Path to DER-formatted PKCS#12 archive. (Unused if serve_tls=false)
# This can be created using openssl:
# openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem -certfile chain_certs.pem
tls_identity_path = "~/.config/darkfi/darkfid_identity.pfx"

# Password for the created TLS identity. (Unused if serve_tls=false)
tls_identity_password = "FOOBAR"

gateway_url = "127.0.0.1:3333"
gateway_subscriber_url = "127.0.0.1:4444"

# Path to mint.params
mint_params = "~/.config/darkfi/cashierd_mint.params"

# Path to spend.params
spend_params = "~/.config/darkfi/cashierd_spend.params"

# Path to cashierd wallet
cashier_wallet_path = "~/.config/darkfi/cashier_wallet.db"

# Password for cashierd wallet
cashier_wallet_password = "TEST_PASSWORD"

# Path to client wallet
client_wallet_path = "~/.config/darkfi/cashier_client_wallet.db"

# Password for client wallet
client_wallet_password = "TEST_PASSWORD"

# Path to database
database_path = "~/.config/darkfi/cashier_database.db"

# The configured networks to use.
[[networks]]
name = "sol"
blockchain = "testnet"

[[networks]]
name = "btc"
blockchain = "testnet"
