rpc_url = "127.0.0.1:9000"
gateway_url = "127.0.0.1:3333"
gateway_subscriber_url = "127.0.0.1:4444"
log_path = "/tmp/cashierd.log"
password = "TEST_PASSWORD"
client_password = "TEST_PASSWORD"

# Whether to listen with TLS or plain TCP
use_tls = false

# Path to DER-formatted PKCS#12 archive.
# This can be created using openssl:
# openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem -certfile chain_certs.pem
tls_identity_path = "~/.config/darkfi/darkfid_identity.pfx"

# Password for the created identity
tls_identity_password = "FOOBAR"

[[networks]]
name = "sol"
blockchain = "testnet"

[[networks]]
name = "btc"
blockchain = "testnet"







