## darkfid configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.

# The address where darkfid should bind its RPC socket
rpc_listen_address = "127.0.0.1:8000"

# Whether to listen with TLS or plain TCP
serve_tls = false

# Path to DER-formatted PKCS#12 archive. (Unused if serve_tls=false)
# This can be created using openssl:
# openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem -certfile chain_certs.pem
tls_identity_path = "~/.config/darkfi/darkfid_identity.pfx"

# Password for the created TLS identity. (Unused if serve_tls=false)
tls_identity_password = "FOOBAR"

# The RPC endpoint for a selected cashier
cashier_rpc_url = "tcp://127.0.0.1:9000"
#cashier_rpc_url = "tls://127.0.0.1:9000"

# Path to the client database
database_path = "~/.config/darkfi/darkfid_client.db"

# Path to the wallet database
wallet_path = "~/.config/darkfi/darkfid_wallet.db"

# The wallet password
wallet_password = "TEST_PASSWORD"
