## gatewayd configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.

# The endpoint where gatewayd will serve its protocol API
protocol_listen_address = "127.0.0.1:3333"

# The endpoint where gatewayd will serve its publisher API
publisher_listen_address = "127.0.0.1:4444"

# Whether to listen with TLS or plain TCP
serve_tls = false

# Path to DER-formatted PKCS#12 archive. (Unused if serve_tls=false)
# This can be created using openssl:
# openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem -certfiles chain_certs.pem
tls_identity_path = "~/.config/darkfi/gatewayd_identity.pfx"

# Password for the created TLS identity. (Unused if serve_tls=false)
tls_identity_password = "FOOBAR"

# Path to database
database_path = "~/.config/darkfi/gatewayd.db"
