[package]
name = "genev"
description = "Generic Event example CLI"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["event-graph", "rpc", "bs58"]}
darkfi-serial = {path = "../../../src/serial"}

async-std = {version = "1.12.0", features = ["attributes"]}
clap = {version = "4.2.7", features = ["derive"]}
log = "0.4.17"
simplelog = "0.12.1"
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
url = "2.3.1"

