[package]
name = "sapvi"
version = "0.1.0"
authors = ["narodnik <x@x.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.7"
group = "0.7"
bellman = { version = "0.7", default-features = false, features = ["groth16"] }
bls12_381 = "0.2"
jubjub = "0.4"

zcash_primitives = { git = "https://github.com/zcash/librustzcash" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash" }
#bench-utils = { git = "https://github.com/scipr-lab/zexe", features = ["print-trace"]}
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.9.1"
rand_xorshift = "0.2"
blake2s_simd = "0.5"

[[bin]]
name = "sha256"
path = "src/sha256.rs"

[[bin]]
name = "pedersen_hash"
path = "src/pedersen_hash.rs"

[[bin]]
name = "mimc"
path = "src/mimc.rs"

[[bin]]
name = "blake"
path = "src/blake.rs"

[[bin]]
name = "zec"
path = "src/zec.rs"
