[package]
name = "sapvi"
version = "0.1.0"
authors = ["narodnik <x@x.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = { git = "https://github.com/zcash/librustzcash" }
group = { git = "https://github.com/zcash/librustzcash" }
pairing = { git = "https://github.com/zcash/librustzcash" }
bellman = { git = "https://github.com/zcash/librustzcash" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash" }
bls12_381 = { git = "https://github.com/zcash/librustzcash" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash" }
jubjub = { git = "https://github.com/zcash/librustzcash" }
#bench-utils = { git = "https://github.com/scipr-lab/zexe", features = ["print-trace"]}
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.9.1"
rand_xorshift = "0.2"

[[bin]]
name = "sha256"
path = "src/sha256.rs"

[[bin]]
name = "mimc"
path = "src/mimc.rs"

[[bin]]
name = "zec"
path = "src/zec.rs"
