[package]
name = "darkfi"
version = "0.2.0"
homepage = "https://dark.fi"
description = "Anonymous. Uncensored. Sovereign."
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[lib]
name = "drk"

[dependencies.halo2_gadgets]
git = "https://github.com/parazyd/halo2_gadgets.git"
rev = "b45c527276bb2309f3b256eb5f45ccdcc5bd8c0f"
features = ["dev-graph", "test-dependencies"]

[dependencies.rocksdb]
# TODO: Revert to upstream after bd966750ec861d687913d59a9939a1408ac53131 is merged.
git = "https://github.com/parazyd/rust-rocksdb"
rev = "bd966750ec861d687913d59a9939a1408ac53131"
default-features = false
features = ["zstd"]

[dependencies]
# Crypto
halo2 = {version = "=0.1.0-beta.1", features = ["dev-graph", "gadget-traces", "sanity-checks"]}
incrementalmerkletree = "0.2.0"
pasta_curves = "0.2.1"
rand = "0.8.4"
num-bigint = {version = "0.4.3", features = ["rand", "serde"]}
blake2b_simd = "1.0.0"
group = "0.11.0"
crypto_api_chachapoly = "0.5.0"
arrayvec = "0.7.2"
sha2 = "0.9.8"
ripemd160 = "0.9.1"

# Encoding and parsing
bincode = "1.3.3"
bs58 = "0.4.0"
bytes = "1.1.0"
hex = "0.4.3"
toml = "0.5.8"
url = "2.2.2"
serde_json = "1.0.72"
serde = {version = "1.0.130", features = ["derive"]}

# Async
async-std = "1.10.0"
async-trait = "0.1.51"
async-channel = "1.6.1"
easy-parallel = "3.1.0"
native-tls = "0.2.8"
async-native-tls = "0.4.0"
async-executor = "1.4.1"
futures = "0.3.17"
smol = "1.2.5"

# Utilities
anyhow = "1.0.49"
clap = "2.34.0"
dirs = "4.0.0"
failure = "0.1.8"
lazy_static = "1.4.0"
log = "0.4.14"
num_cpus = "1.13.0"
simplelog = "0.11.1"
signal-hook = "0.3.10"
signal-hook-async-std = "0.2.1"
subtle = "2.4.1"
thiserror = "1.0.30"
prettytable-rs = "0.8.0"

# Used for Websockets client implementation.
async-tungstenite = "0.16.0"
tungstenite = "0.16.0"

# Used for wallet management.
sqlx = {git = "https://github.com/launchbadge/sqlx", rev = "d258e8c681affe40319b317f0993157b405f835b", features = ["runtime-async-std-native-tls", "sqlite"]}
libsqlite3-sys = {version = "0.23.1", features = ["bundled-sqlcipher"]}

# Used for gatewayd network transport.
zeromq = {version = "0.3.1", default-features = false, features = ["async-std-runtime", "all-transport"]}

# Cashier Bitcoin dependencies
bdk = {version = "0.14.0", optional = true}
bitcoin = {version = "0.27.1", optional = true}
secp256k1 = {version = "0.20.3", default-features = false, features = ["rand-std"], optional = true}

# Cashier Ethereum dependencies
hash-db = {version = "0.15.2", optional = true}
keccak-hasher = {version = "0.15.3", optional = true}

# Cashier Solana dependencies
solana-client = {version = "1.8.11", optional = true}
solana-sdk = {version = "1.8.11", optional = true}
spl-associated-token-account = {version = "1.0.3", features = ["no-entrypoint"], optional = true}
spl-token = {version = "3.2.0", features = ["no-entrypoint"], optional = true}

# Darkpulse and tui dependencies
aes-gcm = {version = "0.9.4", optional = true}
chrono = {version = "0.4.19", optional = true}
rusqlite = {version = "0.26.3", optional = true}
crossbeam-channel = { version = "0.5.1", optional = true}
libc = { version = "0.2.112", optional = true}
termion = { version = "1.5.6", optional = true}

[features]
btc = ["bdk", "bitcoin", "secp256k1"]
eth = ["keccak-hasher", "hash-db"]
sol = ["solana-sdk", "solana-client", "spl-token", "spl-associated-token-account"]
darkpulse = ["aes-gcm", "chrono","rusqlite"]
tui = ["termion", "chrono","libc", "crossbeam-channel"]

[[bin]]         
name = "darkpulse"    
required-features = ["darkpulse"]

[[bin]]         
name = "eth"    
required-features = ["eth"]

[[bin]]         
name = "tui_ex"    
required-features = ["tui"]

[[example]]
name = "net"
path = "example/net.rs"
