[package]
name = "darkfi"
version = "0.2.0"
homepage = "https://dark.fi"
description = "Anonymous. Uncensored. Sovereign."
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[lib]
name = "drk"

[dependencies.halo2]
version = "=0.1.0-beta.1"
features = ["dev-graph", "gadget-traces", "sanity-checks"]

[dependencies.halo2_gadgets]
git = "https://github.com/parazyd/halo2_gadgets.git"
rev = "8238cb3471b798c76dd53b278524fc80685c7d4f"
features = ["dev-graph", "test-dependencies"]

[dependencies.rocksdb]
git = "https://github.com/parazyd/rust-rocksdb"
rev = "bd966750ec861d687913d59a9939a1408ac53131"
default-features = false
features = ["lz4"]

[dependencies]
pasta_curves = "0.2.1"
rand = "0.8.4"
num-bigint = "0.4.2"
blake2b_simd = "0.5.11"
blake2s_simd = "0.5.11"
group = "0.11.0"
crypto_api_chachapoly = "0.5.0"

hex = "0.4.3"
bs58 = "0.4.0"
toml = "0.5.8"
url = "2.2.2"
serde_json = "1.0.68"
serde = {version = "1.0.130", features = ["derive"]}

async-std = "1.10.0"
async-trait = "0.1.51"
async-channel = "1.6.1"
native-tls = "0.2.8"
async-native-tls = "0.3.3"
async-executor = "1.4.1"
futures = "0.3.17"
smol = "1.2.5"

log = "0.4.14"

lazy_static = "1.4.0"

tungstenite = "0.15.0"
async-tungstenite = "0.15.0"

rusqlite = {version = "0.26.1", features = ["bundled-sqlcipher"]}
zeromq = {version = "0.3.0", default-features = false, features = ["async-std-runtime", "all-transport"]}
