[package]
name = "darkfi"
version = "0.1.0"
authors = ["darkfi <dev@dark.fi>"]
edition = "2018"

[lib]
name = "drk"

[dependencies]
ff = "0.8"
group = "0.8"
bellman = { version = "0.8", default-features = false, features = ["groth16"] }
bls12_381 = "0.3.1"
jubjub = "0.5.1"
bs58 = "0.4.0"

zcash_primitives = "0.5.0"
zcash_proofs = "0.5.0"
# zcash_primitives = { git = "https://github.com/zcash/librustzcash" }
#zcash_proofs = { git = "https://github.com/zcash/librustzcash" }
#zcash_proofs = { git = "https://github.com/narodnik/librustzcash" }
#bench-utils = { git = "https://github.com/scipr-lab/zexe", features = ["print-trace"]}
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.9.1"
rand_xorshift = "0.2"
blake2s_simd = "0.5"
blake2b_simd = "0.5.11"
crypto_api_chachapoly = "0.4"
bitvec = "0.18"
bimap = "0.5.2"
async-trait = "0.1.42"
multimap = "0.8.2"

hex = "0.4.2"
num_enum = "0.5.0"

lazy_static = "1.4.0"
itertools = "0.8.0"
#fnv = "1.0.6"
regex = "1"

simplelog = "0.7.4"
clap = "3.0.0-beta.1"
failure = "0.1.8"
failure_derive = "0.1.8"
log = "0.4"
ctrlc = "3.1.7"
serde_json = "1.0.61"
owning_ref = "0.4.1"
signal-hook = "0.3.8"

smol = "1.2.4"
futures = "0.3.5"
async-channel = "1.4.2"
async-executor = "1.4.0"
async-dup = "1.1.0"
async-std = "1.6.2"
async-rwlock = "1.3.0"
easy-parallel = "3.1.0"

jsonrpc-core = "16.0.0"
surf = "2.2.0"
http-types = "2.9.0"
async-h1 = "2.3.0"
async-native-tls = "0.3.3"
toml = "0.5.8"

# serde
serde = { version = "1.0.126", features = ["derive"]}

# zmq
zeromq = { git="https://github.com/zeromq/zmq.rs", default-features = false, features = ["async-std-runtime", "all-transport"] }
bytes = "1.0.1"

# wallet deps
rocksdb = "0.16.0"
dirs = "3.0.2"

bitcoin = "0.27.0"
secp256k1 = "0.20.3"
electrum-client = "0.8.0"

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled", "sqlcipher"]

[[bin]]
name = "lisp"
path = "lisp/lisp.rs"

[[bin]]
name = "zkvm"
path = "src/bin/zkvm.rs"

[[bin]]
name = "mimc"
path = "src/old/mimc.rs"

[[bin]]
name = "mint-classic"
path = "src/bin/mint-classic.rs"

[[bin]]
name = "spend-classic"
path = "src/bin/spend-classic.rs"

[[bin]]
name = "tx"
path = "src/bin/tx.rs"

[[bin]]
name = "gatewayd"
path = "src/bin/gatewayd.rs"

[[bin]]
name = "cashierd"
path = "src/bin/cashierd.rs"

[[bin]]
name = "darkfid"
path = "src/bin/darkfid.rs"


[[bin]]
name = "drk"
path = "src/bin/drk.rs"

[profile.release]
debug = 1
