[package]
name = "sapvi"
version = "0.1.0"
authors = ["narodnik <x@x.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.8"
group = "0.8"
bellman = { version = "0.8", default-features = false, features = ["groth16"] }
bls12_381 = "0.3.1"
jubjub = "0.5.1"

zcash_primitives = { git = "https://github.com/zcash/librustzcash" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash" }
#zcash_proofs = { git = "https://github.com/narodnik/librustzcash" }
#bench-utils = { git = "https://github.com/scipr-lab/zexe", features = ["print-trace"]}
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.9.1"
rand_xorshift = "0.2"
blake2s_simd = "0.5"
bitvec = "0.18"

hex = "0.4.2"

[[bin]]
name = "sha256"
path = "src/sha256.rs"

[[bin]]
name = "pedersen_hash"
path = "src/pedersen_hash.rs"

[[bin]]
name = "mimc"
path = "src/mimc.rs"

[[bin]]
name = "blake"
path = "src/blake.rs"

[[bin]]
name = "zec"
path = "src/zec.rs"

[[bin]]
name = "simple"
path = "src/simple.rs"

[[bin]]
name = "mint"
path = "src/mint.rs"

[[bin]]
name = "spend"
path = "src/spend.rs"

[[bin]]
name = "eq"
path = "src/eq.rs"

[[bin]]
name = "basic"
path = "src/basic_minimal.rs"

[[bin]]
name = "vmtest"
path = "src/vmtest.rs"

[[bin]]
name = "jubjub"
path = "src/jubjub.rs"

[[bin]]
name = "bits"
path = "src/bits.rs"

[[bin]]
name = "zkmimc"
path = "src/zkmimc.rs"

