## drk client configuration file
##
## Please make sure you go through all the settings so you can configure
## your client properly.

# The RPC endpoint where darkfid is listening on
darkfid_rpc_url = "tcp://127.0.0.1:8000"
#darkfid_rpc_url = "tls://127.0.0.1:8000"
