[package]
name = "fud"
description = "File-sharing Utility Daemon, using DHT for records discovery."
version = "0.4.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["dht", "rpc"]}
darkfi-serial = {path = "../../../src/serial"}

# Async
async-std = "1.12.0"
async-trait = "0.1.64"
ctrlc = { version = "3.2.4", features = ["termination"] }
easy-parallel = "3.2.0"
smol = "1.3.0"

# Misc
blake3 = "1.3.3"
log = "0.4.17"
serde_json = "1.0.91"
simplelog = "0.12.0"
url = "2.3.1"

# Argument parsing
serde = {version = "1.0.152", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
