[package]
name = "dhtd"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["dht"]

[dependencies]
async-channel = "2.3.1"
async-executor = "1.12.0"
async-std = "1.12.0"
async-trait = "0.1.81"
blake3 = "1.5.1"
ctrlc = { version = "3.4.4", features = ["termination"] }
easy-parallel = "3.3.1"
futures-lite = "2.3.0"
log = "0.4.22"
serde_json = "1.0.120"
simplelog = "0.12.2"
url = "2.5.2"

# Argument parsing
serde = "1.0.204"
serde_derive = "1.0.204"
structopt = "0.3.26"
structopt-toml = "0.5.1"

[workspace]

[lints]
workspace = true

