[package]
name = "dhtd"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["dht"]

[dependencies]
async-channel = "1.8.0"
async-executor = "1.5.1"
async-std = "1.12.0"
async-trait = "0.1.68"
blake3 = "1.3.3"
ctrlc = { version = "3.2.5", features = ["termination"] }
easy-parallel = "3.3.0"
futures-lite = "1.13.0"
log = "0.4.17"
serde_json = "1.0.96"
simplelog = "0.12.1"
url = "2.3.1"

# Argument parsing
serde = "1.0.160"
serde_derive = "1.0.160"
structopt = "0.3.26"
structopt-toml = "0.5.1"

[workspace]
