[package]
name = "crypsinous_playground"
version = "0.1.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
darkfi = {path = "../../../", features = ["crypto", "node"]}
darkfi-sdk = {path = "../../../src/sdk"}
dashu = { version = "0.2.0", git = "https://github.com/ertosns/dashu" }
halo2_gadgets = "0.2.0"
halo2_proofs = "0.2.0"
incrementalmerkletree = "0.3.0"
pasta_curves = "0.4.1"

# Async
async-std = "1.12.0"
async-trait = "0.1.59"
ctrlc = { version = "3.2.3", features = ["termination"] }
easy-parallel = "3.2.0"
smol = "1.3.0"

# Argument parsing
serde = "1.0.148"
serde_derive = "1.0.148"
structopt = "0.3.26"
structopt-toml = "0.5.1"

# Misc
blake3 = "1.3.3"
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
