[package]
name = "crypsinous_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.3.1"
darkfi = {path = "../../../", features = ["crypto"]}
darkfi-sdk = {path = "../../../src/sdk"}
dashu = { version = "0.2.0", git = "https://github.com/ertosns/dashu" }
halo2_gadgets = "0.2.0"
halo2_proofs = "0.2.0"
incrementalmerkletree = "0.3.0"
pasta_curves = "0.4.0"
rand = "0.8.5"

# Misc
log = "0.4.17"
simplelog = "0.12.0"

[workspace]
