## crypsinous_playground configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Path to the wallet database
#wallet_path = "~/.config/darkfi/crypsinous_playground/wallet.db"

# Password for the wallet database
#wallet_pass = "changeme"
