[package]
name = "gatewayd"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path= "../../"
features = ["node"]

[dependencies]
# Async
smol = "1.2.5"
async-std = "1.11.0"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Misc
clap = {version = "3.1.6", features = ["derive"]}
log = "0.4.16"
num_cpus = "1.13.1"
simplelog = "0.11.2"

# Encoding and parsing
serde = {version = "1.0.136", features = ["derive"]}
