[package]
name = "evgrd"
description = "Event graph daemon"
version = "0.5.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://codeberg.org/darkrenaissance/darkfi"

[[bin]]
name = "evgrd"
path = "bin/evgrd.rs"

[[bin]]
name = "test"
path = "bin/test.rs"

[dependencies]
darkfi = {path = "../../", features = ["event-graph"]}
darkfi-serial = {path = "../../src/serial", features = ["async"]}

# Event Graph DB
sled-overlay = "0.1.3"

# Crypto
blake3 = "1.5.4"

# Misc
log = "0.4.22"
url = "2.5.2"

# Daemon
smol = "2.0.1"

#[lints]
#workspace = true

# Temp stuff
[workspace]

