[package]
name = "evgrd"
description = "Event graph daemon"
version = "0.5.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://codeberg.org/darkrenaissance/darkfi"

[[bin]]
name = "evgrd"
path = "bin/evgrd.rs"

[[bin]]
name = "test"
path = "bin/test.rs"

[dependencies]
darkfi = {path = "../../", features = ["async-daemonize", "event-graph", "rpc", "zk"]}
darkfi-sdk = {path = "../../src/sdk", features = ["async"]}
darkfi-serial = {path = "../../src/serial", features = ["async"]}
futures-lite = "2.3.0"
libc = "0.2.158"

# Event Graph DB
sled-overlay = "0.1.3"

# TLS
async-trait = "0.1.81"
futures = "0.3.30"
futures-rustls = {version = "0.26.0", default-features = false, features = ["logging", "tls12", "ring"]}
rustls-pemfile = "2.1.3"

# Crypto
blake3 = "1.5.4"
bcrypt = "0.15.1"
crypto_box = {version = "0.9.1", features = ["std", "chacha20"]}
rand = "0.8.5"

# Misc
log = "0.4.22"
url = "2.5.2"

# Encoding and parsing
bs58 = "0.5.1"
toml = "0.8.19"
semver = "1.0.23"

# Daemon
easy-parallel = "3.3.1"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.17"
simplelog = "0.12.2"
smol = "2.0.1"

# Argument parsing
serde = {version = "1.0.209", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"

# See https://github.com/rust-mobile/android-rs-glue/issues/193
[target.aarch64-linux-android.dependencies]
openssl = { version = "*", features = ["vendored"] }
rusqlite = {version = "0.31.0", features = ["bundled"]}

#[lints]
#workspace = true

# Temp stuff
[workspace]
[patch.crates-io]
halo2_proofs = {git="https://github.com/parazyd/halo2", branch="v4"}
halo2_gadgets = {git="https://github.com/parazyd/halo2", branch="v4"}

