[[nodes]]
name = "darkirc"
host = "localhost"
port = 26660
type = "NORMAL"

[[nodes]]
name = "taud"
host = "localhost"
port = 23330
type = "NORMAL"

#[[nodes]]
#name = "evgrd"
#host = "localhost"
#port = 26690
#type = "NORMAL"

#[[nodes]]
#name = "lilith"
#host = "localhost"
#port = 18927
#type = "LILITH"
