[package]
name = "ping"
version = "0.1.0"
homepage = "https://dark.fi"
description = "Ping tool for servers"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../", features = ["net"]}
darkfi-serial = {path = "../../src/serial"}
url = {version = "2.5.2", features = ["serde"]}
smol = "2.0.0"

[lints]
workspace = true
