[package]
name = "cashierd"
version = "0.4.1"
homepage = "https://dark.fi"
description = "cashier daemon for DarkFi"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["wallet", "node", "rpc"]

[dependencies]
# Async
smol = "1.3.0"
futures = "0.3.28"
async-std = "1.12.0"
async-trait = "0.1.68"
async-channel = "1.8.0"
async-executor = "1.5.1"
easy-parallel = "3.3.0"

# Crypto
rand = "0.8.5"

# Misc
clap = {version = "4.2.2", features = ["derive"]}
log = "0.4.17"
num_cpus = "1.15.0"
simplelog = "0.12.1"
thiserror = "1.0.40"
url = "2.3.1"

# Encoding and parsing
serde = {version = "1.0.160", features = ["derive"]}
serde_json = "1.0.96"

# Bitcoin bridge dependencies
bdk = {version = "0.28.0", optional = true}
anyhow = {version = "1.0.70", optional = true}
bitcoin = {version = "0.30.0", optional = true}
secp256k1 = {version = "0.27.0", default-features = false, features = ["rand-std"], optional = true}

# Ethereum bridge dependencies
hex = {version = "0.4.3", optional = true}
hash-db = {version = "0.16.0", optional = true}
lazy_static = {version = "1.4.0", optional = true}
keccak-hasher = {version = "0.16.0", optional = true}
num-bigint = {version = "0.4.3", features = ["rand", "serde"], optional = true}

# Solana bridge dependencies
native-tls = {version = "0.2.11", optional = true}
async-native-tls = {version = "0.5.0", optional = true}
solana-client = {version = "1.14.17", optional = true}
solana-sdk = {version = "1.14.13", optional = true}
spl-associated-token-account = {version = "1.1.3", features = ["no-entrypoint"], optional = true}
spl-token = {version = "3.5.0", features = ["no-entrypoint"], optional = true}
tungstenite = {version = "0.19.0", optional = true}

[features]
btc = [
    "anyhow",
    "bdk",
    "bitcoin",
    "secp256k1",
]

eth = [
    "num-bigint",
    "keccak-hasher",
    "hash-db",
    "lazy_static",
    "hex",
]

sol = [
    "async-native-tls",
    "native-tls",
    "solana-client",
    "solana-sdk",
    "spl-associated-token-account",
    "spl-token",
    "tungstenite",
]
