[package]
name = "crdt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.darkfi]
path = "../../../"
features = ["net"]

[dependencies]
serde = {version = "1.0.136", features = ["derive"]}
# Async
smol = "1.2.5"
futures = "0.3.21"
async-std = "1.10.0"
async-trait = "0.1.52"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Crypto
rand = "0.8.5"

# Misc
clap = "3.1.6"
log = "0.4.14"
simplelog = "0.11.2"


[workspace]
