## generic node configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

## P2P network settings
[net]
# P2P accept addresses the instance listens on for inbound connections
inbound = ["tcp+tls://0.0.0.0:38970"]

# Peer nodes to manually connect to
peers = [
    "tcp+tls://0.0.0.0:38967",
    "tcp+tls://0.0.0.0:38968",
    "tcp+tls://0.0.0.0:38969",
]

# Allow localnet hosts
localnet = true
