[package]
name = "raft_p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]


[dependencies]
darkfi = {path = "../../../", features = ["net", "rpc"]}

# Async
async-channel = "1.6.1"
async-std = {version = "1.11.0", features = ["attributes"]}
futures = "0.3.21"
async-executor = "1.4.1"
async-trait = "0.1.53"

# Misc
borsh = "0.9.3"
log = "0.4.16"
rand = "0.8.5"

[dev-dependencies]
clap = {version = "3.1.6", features = ["derive"]}
easy-parallel = "3.2.0"
simplelog = "0.12.0-alpha1"
smol = "1.2.5"
