[package]
name = "drk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darkfi = {path= "../../"}

# Encoding and parsing
serde_json = "1.0.72"
serde = {version = "1.0.130", features = ["derive"]}

# Async
async-std = {version = "1.10.0", features = ["attributes"]}
async-executor = "1.4.1"
futures = "0.3.17"
smol = "1.2.5"


# Utilities
clap = { version = "3.0.0", features = ["derive"] }
prettytable-rs = "0.8.0"
simplelog = "0.11.1"
log = "0.4.14"
