[package]
name = "drk"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path= "../../"
features = ["rpc"]

[dependencies]
# Async
async-std = {version = "1.11.0", features = ["attributes"]}

# Misc
clap = {version = "3.1.6", features = ["derive"]}
log = "0.4.16"
simplelog = "0.11.2"
prettytable-rs = "0.8.0"
url = "2.2.2"

# Encoding and parsing
serde_json = "1.0.79"
serde = {version = "1.0.136", features = ["derive"]}
