[package]
name = "drk"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Command-line client for darkfid"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
bs58 = "0.4.0"
clap = {version = "3.2.20", features = ["derive"]}
darkfi = {path = "../../", features = ["crypto", "util", "rpc", "wasm-runtime", "zkas"]}
indicatif = "0.17.1"
log = "0.4.17"
pasta_curves = "0.4.0"
prettytable-rs = "0.9.0"
rand = "0.8.5"
serde_json = "1.0.85"
simplelog = "0.12.0"
url = "2.3.1"
