[package]
name = "drk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darkfi = {path= "../../"}

# Async
async-executor = "1.4.1"
futures = "0.3.17"
smol = "1.2.5"

# Utilities
clap = { version = "3.0.0", features = ["derive"] }
prettytable-rs = "0.8.0"
