[package]
name = "map"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["rpc"]

[dependencies]
# tui
termion = "1.5.6"
tui = "0.16.0"

# async
smol = "1.2.4"

#misc
rand = "0.6.5"
