[package]
name = "map"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["rpc"]

[dependencies]
# Tui
termion = "1.5.6"
tui = "0.16.0"

# Async
smol = "1.2.4"
async-std = {version = "1.10.0", features = ["attributes"]}

# Misc
rand = "0.6.5"
log = "0.4.14"

# Encoding and parsing
serde_json = "1.0.74"
