[package]
name = "map"
version = "0.1.0"
edition = "2021"

[dependencies]
darkfi = { path = "../../" , features = ['tui']}
smol = "1.2.5"
tui = "0.16.0"
termion = "1.5"
async-executor = "1.4.1"
easy-parallel = "3.1.0"
async-std = "1.10.0"
async-channel = "1.6.1"
num_cpus = "1.13.0"
rand = "0.8.4"
