[package]
name = "genevd"
description = "Generic Event example daemon"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["event-graph", "rpc", "bs58", "util"]}
darkfi-serial = {path = "../../../src/serial"}

async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.68"
ctrlc = { version = "3.4.0", features = ["termination"] }
easy-parallel = "3.3.0"
simplelog = "0.12.1"
smol = "1.3.0"
log = "0.4.18"
url = "2.4.0"

# Argument parsing
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
structopt = "0.3.26"
structopt-toml = "0.5.1"