[package]
name = "gg"
version = "0.4.1"
description = """\
Genesis Generator, a command-line utility to generate,\
display and verify a base64 encoded Darkfi genesis block\
"""
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
# Darkfi
darkfi = {path = "../../../", features = ["bs58", "validator"]}
darkfi_money_contract = {path = "../../../src/contract/money", features = ["no-entrypoint", "client"]}
darkfi-contract-test-harness = {path = "../../../src/contract/test-harness"}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = {path = "../../../src/serial"}

# Misc
async-std = {version = "1.12.0", features = ["attributes"]}
bs58 = "0.5.1"
clap = {version = "4.4.11", features = ["derive"]}
sled = "0.34.7"

[patch.crates-io]
halo2_proofs = {git="https://github.com/parazyd/halo2", branch="v4"}
halo2_gadgets = {git="https://github.com/parazyd/halo2", branch="v4"}
