[package]
name = "darkwikid"
version = "0.4.0"
homepage = "https://dark.fi"
description = "Reference daemon for a decentralized P2P wiki"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = "1.12.0"
async-trait = "0.1.57"
blake3 = "1.3.1"
bs58 = "0.4.0"
darkfi = {path = "../../../", features = ["raft", "rpc", "util"]}
darkfi-serial = {path = "../../../src/serial"}
dryoc = "0.3.14"
easy-parallel = "3.2.0"
futures = "0.3.24"
fxhash = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.17"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.85"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.14"
simplelog = "0.12.0"
structopt = "0.3.26"
structopt-toml = "0.5.1"
smol = "1.2.5"
toml = "0.5.9"
unicode-segmentation = "1.10.0"
url = "2.3.1"
