[package]
name = "merkletree_null_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]

darkfi = {path="../../../", features=["node"]}
darkfi-sdk = {path="../../../src/sdk"}
darkfi-serial = {path="../../../src/serial"}

rand = "0.8.5"
pasta_curves = "0.4.0"
incrementalmerkletree = "0.3.0"

serde_json = "1.0.87"

[workspace]

