[package]
name = "darkwallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
miniquad = { git = "https://github.com/not-fl3/miniquad" }
# Currently latest version links to freetype-sys 0.19 but we use 0.21
#harfbuzz-sys = "0.6.1"
#harfbuzz-sys = { git = "https://github.com/servo/rust-harfbuzz", features = ["bundled"] }
harfbuzz-sys = { git = "https://github.com/narodnik/rust-harfbuzz", features = ["bundled"] }
# Old and crap
#harfbuzz_rs = { git = "https://github.com/narodnik/hbrs2.git", features = ["freetype"] }
freetype-rs = { version = "0.37.0", features = ["bundled"] }
image = "0.25.2"
log = "0.4.22"
glam = "0.28.0"
#zmq = "0.10.0"
#async_zmq = "0.4.0"
zeromq = { version = "0.4.0", default-features = false, features = ["async-std-runtime", "all-transport"] }
darkfi-serial = { git = "https://codeberg.org/darkrenaissance/darkfi" }
thiserror = "1.0.61"
smol = "2.0.0"
atomic_float = "1.0.0"
async-channel = "2.3.1"
easy-parallel = "3.3.1"
rand = "0.8.5"
async-lock = "3.4.0"
futures = "0.3.30"
async-recursion = "1.1.1"
colored = "2.1.0"
#rustpython-vm = "0.3.1"
sled = "0.34.7"

[patch.crates-io]
freetype-rs = { git = "https://github.com/narodnik/freetype-rs" }
freetype-sys = { git = "https://github.com/narodnik/freetype-sys" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"

[target.'cfg(target_os = "linux")'.dependencies]
simplelog = "0.12.1"

[package.metadata.android.activity_attributes]
"android:exported" = "true"
"android:windowSoftInputMode" = "adjustResize"

[lints]
workspace = true

[workspace.lints.clippy]

[package.metadata.android]
package_name = "darkfi.darkwallet"
label = "DarkWallet"
res = "res"
icon = "@mipmap/ic_launcher"
assets = "assets"

[[package.metadata.android.permission]]
name = "android.permission.INTERNET"
[[package.metadata.android.permission]]
name = "android.permission.ACCESS_NETWORK_STATE"
