[package]
name = "darkwallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
#miniquad = "0.4.0-alpha"
#miniquad = { git = "https://github.com/not-fl3/miniquad" }
miniquad = { git = "https://github.com/narodnik/miniquad.git" }
#harfbuzz_rs = { git = "https://github.com/narodnik/harfbuzz_rs.git", features = ["freetype"] }
harfbuzz_rs = { git = "https://github.com/narodnik/hbrs2.git", features = ["freetype"] }
freetype-rs = { git = "https://github.com/narodnik/freetype-rs.git" }
#harfbuzz = { version = "0.6.0", features = ["bundled"] }
#harfbuzz_rs = "2.0.1"
#freetype-rs = "0.36.0"
freetype-sys = "0.20.1"
image = "0.25.1"
log = "0.4.21"
glam = "0.27.0"
zmq = "0.10.0"
#darkfi-serial = { path = "../../src/serial" }
darkfi-serial = { git = "https://codeberg.org/darkrenaissance/darkfi.git" }
thiserror = "1.0.61"
# Only for async Mutex
smol = "2.0.0"
atomic_float = "1.0.0"
async-channel = "2.3.1"
easy-parallel = "3.3.1"
crossbeam-skiplist = "0.1"
rand = "0.8.5"

#rustpython-vm = "0.3.1"

#[patch."https://github.com/narodnik/harfbuzz_rs.git"]
#freetype-rs = { path = "/tmp/freetype-rs/" }

[patch.crates-io]
freetype-rs = { git = "https://github.com/narodnik/freetype-rs.git" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"

[target.'cfg(target_os = "linux")'.dependencies]
simplelog = "0.12.1"

[package.metadata.android.activity_attributes]
"android:exported" = "true"
"android:windowSoftInputMode" = "adjustResize"

[lints]
workspace = true

[workspace.lints.clippy]

