[package]
name = "crypsinous"
version = "0.1.0"
description = "crypsinous blockchain simulation"
authors = ["mohab-metwally@riseup.net"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = {version = "1.11.0", features = ["attributes"]}
darkfi = {path = "../../", features = ["node", "tx"]}
url = "2.2.2"
thread = "0.1.0"
futures = "0.3.21"
#url = {version = "2.2.2", features = ["serde"], optional = true}
