[package]
name = "darkfi-derive"
version = "0.3.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "0.1.5"
proc-macro2 = "1.0.36"
syn = {version = "1.0.89", features = ["full", "fold"]}

darkfi-derive-internal = {path = "../derive-internal"}
