[package]
name = "zkas"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path= "../../"
features = ["zkas"]

[dependencies]
# Misc
anyhow = "1.0.52"
clap = {version = "3.0.7", features = ["derive"]}
