[book]
authors = ["DarkFi"]
language = "en"
multilingual = false
src = "src"
title = "The DarkFi Book"

[output.html]
copy-fonts = true
default-theme = "ayu"
preferred-dark-theme = "ayu"
theme = "theme"

[output.html.playground]
runnable = false

[output.katex]

[preprocessor.katex]
