[package]
name = "ircd"
description = "P2P IRC daemon"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../", features = ["net", "rpc", "bs58"]}
darkfi-serial = {path = "../../src/serial"}

# Async
smol = "1.3.0"
futures = "0.3.28"
futures-rustls = "0.24.0"
rustls-pemfile = "1.0.2"
async-std = "1.12.0"
async-trait = "0.1.68"
easy-parallel = "3.3.0"
async-recursion = "1.0.4"

# Crypto
crypto_box = "0.8.2"
rand = "0.8.5"

# Misc
clap = {version = "4.3.3", features = ["derive"]}
log = "0.4.19"
simplelog = "0.12.1"
ctrlc = { version = "3.4.0", features = ["termination"] }
url = "2.4.0"
chrono = "0.4.26"
ripemd = "0.1.3"

# Encoding and parsing
serde_json = "1.0.96"
serde = {version = "1.0.164", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
bs58 = "0.5.0"
toml = "0.7.4"
hex = "0.4.3"
