## JSON-RPC listen URL
#rpc_listen="tcp://127.0.0.1:11055"

## IRC listen URL
#irc_listen="tcp://127.0.0.1:6667"
#irc_listen="tls://0.0.0.0:6697"

## TLS certificate path if IRC acceptor uses TLS (optional)
#irc_tls_cert = "/etc/letsencrypt/ircd/fullchain.pem"

## TLS secret key path if IRC acceptor uses TLS (optional)
#irc_tls_secret = "/etc/letsencrypt/ircd/privkey.pem"

## List of channels to autojoin for new client connections
autojoin = ["#dev", "#memes", "#philosophy", "#markets", "#math", "#random"]

## Daemon specific password (optional, but once you configure it,
## it is required from the client side)
#password="CHANGE_ME"

## P2P net settings
[net]
## Connection slots
outbound_connections=5

## P2P accept addresses
#inbound=["tls://0.0.0.0:11002"]
# ipv6 version:
#inbound=["tls://[::]:11002"]

## P2P external addresses
## Put your IPs or hostnames here
## This is how people can reach you on the inbound port configured above
## You can also put an ipv6 address :)
#external_addr=["tls://XXX.XXX.XXX.XXX:11002"]
# ipv6 version:
#external_addr=["tls://[ipv6 address here]:11002"]

## Manually configured peers to connect to
#peers=["tls://127.0.0.1:11003"]

## Seed nodes to connect to 
seeds = ["tls://lilith0.dark.fi:25551", "tls://lilith1.dark.fi:25551"]

## Only used for debugging. Compromises privacy when set.
#node_id = "foo"

## these are the default configuration for the p2p network
#manual_attempt_limit=0
#seed_query_timeout_seconds=8
#connect_timeout_seconds=10
#channel_handshake_seconds=4
#channel_heartbeat_seconds=10

## Per-channel settings
#[channel."#foo"]
## Create with `ircd --gen-secret`
#secret = "7CkVuFgwTUpJn5Sv67Q3fyEDpa28yrSeL5Hg2GqQ4jfM"
## Topic to set for the channel
#topic = "DarkFi Foo Stuff"

## Contacts list
# Shared secrets that encrypt direct communication between two nicknames on
# the network.
# These are in the form of secret:[nick0,nick1], which means that the same
# shared secret will be used for all the nicknames in the list.
[contact."7CkVuFgwTUpJn5Sv67Q3fyEDpa28yrSeL5Hg2GqQ4jfM"]
nicks = ["sneed", "chuck"]
