[package]
name = "sraft"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
async-channel = "1.6.1"
async-std = {version = "1.11.0", features = ["attributes"]}
borsh = "0.9.3"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.16"
rand = "0.8.5"

[dev-dependencies]
async-executor = "1.4.1"
clap = {version = "3.1.6", features = ["derive"]}
easy-parallel = "3.2.0"
simplelog = "0.12.0-alpha1"
smol = "1.2.5"
