[package]
name = "darkfid"
version = "0.4.0"
homepage = "https://dark.fi"
description = "DarkFi node daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = "1.12.0"
async-trait = "0.1.64"
blake3 = "1.3.3"
bs58 = "0.4.0"
ctrlc = { version = "3.2.4", features = ["termination"] }
darkfi = {path = "../../", features = ["blockchain", "wallet", "rpc", "net"]}
darkfi-sdk = {path = "../../src/sdk"}
darkfi-serial = {path = "../../src/serial"}
easy-parallel = "3.2.0"
log = "0.4.17"
serde_json = "1.0.91"
simplelog = "0.12.0"
sled = "0.34.7"
smol = "1.3.0"
sqlx = {version = "0.6.2", features = ["runtime-async-std-rustls", "sqlite"]}
url = "2.3.1"

# Argument parsing
serde = {version = "1.0.152", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
