[package]
name = "darkfid"
version = "0.2.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["node", "rpc", "cli"]

[dependencies]
# Async
smol = "1.2.5"
async-std = "1.10.0"
async-trait = "0.1.52"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Misc
clap = {version = "3.0.7", features = ["derive"]}
url = "2.2.2"
log = "0.4.14"
num_cpus = "1.13.1"
simplelog = "0.11.2"

# Encoding and parsing
serde_json = "1.0.74"
num-bigint = {version = "0.4.3", features = ["serde"]}
# serde = {version = "1.0.130", features = ["derive"]}
# url = "2.2.2"


# # Async
# async-std = "1.10.0"
# async-trait = "0.1.51"
# async-channel = "1.6.1"
# easy-parallel = "3.1.0"
# async-executor = "1.4.1"
# futures = "0.3.17"
# smol = "1.2.5"


# # Utilities
# clap = { version = "3.0.0", features = ["derive"] }
# log = "0.4.14"
# simplelog = "0.11.1"
# thiserror = "1.0.30"
# rand = "0.8.4"
# num_cpus = "1.13.0"
# lazy_static = "1.4.0"
# anyhow = "1.0.49"
# num-bigint = {version = "0.4.3", features = ["rand", "serde"]}
