## darkfid configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Chain to use (testnet, mainnet)
chain = "testnet"

# Path to the wallet database
wallet_path = "~/.config/darkfi/darkfid_wallet_testnet.db"

# Password for the wallet database
#wallet_pass = "changeme"

# Path to the blockchain database directory
database = "~/.config/darkfi/darkfid_blockchain_testnet"

# JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:8340"

# Participate in the consensus protocol
consensus = false

# Enable single-node mode for local testing
single_node = false

# P2P accept addresses for the consensus protocol
#consensus_p2p_accept = ["tls://127.0.0.1:8341"]

# P2P external addresses for the consensus protocol
#consensus_p2p_external = ["tls://127.0.0.1:8341"]

# Connection slots for the consensus protocol
#consensus_slots = 8

# Seed nodes to connect to for the consensus protocol
#consensus_p2p_seed = []

# Seed nodes JSON-RPC listen URL for clock synchronization
#consensus_seed_rpc = []

# Peers to connect to for the consensus protocol
#consensus_p2p_peer = []

# Peers JSON-RPC listen URL for clock synchronization
#consensus_peer_rpc = []

# Prefered transports of outbound connections for the consensus protocol
#consensus_p2p_transports = ["tls", "tcp"]

# P2P accept addresses for the syncing protocol
sync_p2p_accept = ["tls://0.0.0.0:8342"]

# P2P external addresses for the syncing protocol
#sync_p2p_external = ["tls://127.0.0.1:8342"]

# Connection slots for the syncing protocol
sync_slots = 8

# Seed nodes to connect to for the syncing protocol
sync_p2p_seed = ["tls:/lilith0.dark.fi:8342", "tls://lilith1.dark.fi:8342"]

# Peers to connect to for the syncing protocol
#sync_p2p_peer = []

# Prefered transports of outbound connections for the syncing protocol
sync_p2p_transports = ["tls"]

# Enable localnet hosts
localnet = false

# Enable channel log
#channel_log = false

# Whitelisted cashier addresses
#cashier_pub = []

# Whitelisted faucet addresses
faucet_pub = ["3ce5xa3PjuQGFtTaF7AvMJp7fGxqeGRJx7zj3LCwNCkP"]

# Verify system clock is correct
#clock_sync = true
