## darkfid configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.

# Path to the client database
database_path = "~/.config/darkfi/darkfid_client.db"

# Path to the wallet database
wallet_path = "~/.config/darkfi/darkfid_wallet.db"

# The wallet password
wallet_password = "TEST_PASSWORD"

# Path to DER-formatted PKCS#12 archive. (used only with tls url)
# This can be created using openssl:
# openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem -certfile chain_certs.pem
tls_identity_path = "~/.config/darkfi/darkfid_identity.pfx"

# Socks5 server url. eg. `socks5://127.0.0.1:9050` used for tor and nym protocols 
[socks_url]
url = "socks5://127.0.0.1:9050"

# The address where darkfid should bind its RPC socket
[rpc_listener_url]
url="127.0.0.1:8000"
# Password for the created TLS identity or tor password
password = "FOOBAR"

# The endpoint to a gatewayd protocol API
[gateway_url]
url="tcp://testnet.gateway-protocol.dark.fi:3333"

# The endpoint to a gatewayd publisher API
[gateway_pub_url]
url="tcp://testnet.gateway-publish.dark.fi:4444"

# The configured cashiers to use.
[[cashiers]]
# Cashier name
name = "testnet.cashier.dark.fi"
# The selected cashier public key
public_key = "129F9szk9CuMEzBb8VqnoWPuShxayUznAgUBZsGzLyMrkDBHxC3"
# The RPC endpoint for a selected cashier
[cashiers.rpc_url]
url="tls://testnet.cashier.dark.fi:9000"
