[package]
name = "darkfi-sdk"
version = "0.3.0"
homepage = "https://dark.fi"
description = "SDK used for developing smart contracts on DarkFi"
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies.darkfi-serial]
path = "../serial"
features = [
    "derive",
    "pasta_curves",
]

[dependencies]
# Error handling
thiserror = "1.0.37"

# Encoding
bs58 = "0.4.0"

# Cryptography
pasta_curves = "0.4.0"
incrementalmerkletree = "0.3.0"
halo2_gadgets = "0.2.0"
