[package]
name = "darkfi-sdk"
version = "0.4.1"
homepage = "https://dark.fi"
description = "SDK used for developing smart contracts on DarkFi"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[lib]
doctest = false

[dependencies]
# Error handling
thiserror = "1.0.40"

# Serialization
darkfi-serial = {version = "0.4.1", path = "../serial", features = ["derive", "crypto"]}

# Encoding
bs58 = "0.4.0"

# Big float high precision arithmetics
dashu = {version = "0.3.1", optional = true}

# Cryptography
blake2b_simd = "1.0.1"
blake3 = "1.3.3"
chacha20poly1305 = "0.10.1"
halo2_gadgets = "0.3.0"
incrementalmerkletree = "0.3.1"
num-bigint = "0.4.3"
num-traits = "0.2.15"
pasta_curves = "0.5.1"
rand_core = "0.6.4"
sha2 = "0.10.6"

# Misc
lazy_static = "1.4.0"
subtle = "2.4.1"

[dev-dependencies]
halo2_proofs = {version = "0.3.0", features = ["dev-graph", "gadget-traces", "sanity-checks"]}
halo2_gadgets = {version = "0.3.0", features = ["test-dev-graph", "test-dependencies"]}
rand = "0.8.5"

[patch.crates-io]
halo2_proofs = {git="https://github.com/parazyd/halo2", branch="v3"}
