[package]
name = "ecvrf"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
blake3 = "1.3.3"
darkfi-sdk = {path = "../../../src/sdk"}
darkfi = {path = "../../../", features = ["zk"]}
lazy_static = "1.4.0"
rand = "0.8.5"
halo2_gadgets = "0.3.0"

[patch.crates-io]
halo2_proofs = {git="https://github.com/parazyd/halo2", branch="v3"}
