[package]
name = "raft-diag"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
edition = "2021"

[workspace]

[dependencies]
darkfi = {path = "../../../", features = ["raft"]}

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.68"
async-channel = "1.8.0"
async-executor = "1.5.1"
easy-parallel = "3.3.0"
futures = "0.3.28"

# Misc
log = "0.4.17"
simplelog = "0.12.1"
rand = "0.8.5"
chrono = "0.4.24"
thiserror = "1.0.40"
ctrlc = { version = "3.2.5", features = ["termination"] }
url = "2.3.1"
fxhash = "0.2.1"

# Encoding and parsing
serde = {version = "1.0.162", features = ["derive"]}
serde_json = "1.0.96"
structopt = "0.3.26"
hex = "0.4.3"
bs58 = "0.4.0"
toml = "0.7.3"
