[package]
name = "raft-diag"
version = "0.1.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
edition = "2021"

[workspace]

[dependencies]
darkfi = {path = "../../../", features = ["raft"]}

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.59"
async-channel = "1.8.0"
async-executor = "1.5.0"
easy-parallel = "3.2.0"
futures = "0.3.25"

# Misc
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
chrono = "0.4.23"
thiserror = "1.0.37"
ctrlc = { version = "3.2.3", features = ["termination"] }
url = "2.3.1"
fxhash = "0.2.1"

# Encoding and parsing
serde = {version = "1.0.148", features = ["derive"]}
serde_json = "1.0.89"
structopt = "0.3.26"
hex = "0.4.3"
bs58 = "0.4.0"
toml = "0.5.9"
