[package]
name = "dark-forest"
version = "0.1.0"
description = "Minimal Tree implementation using DFS post-order traversal to iterate its leafs."
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
thiserror = "1.0.50"
