[package]
name = "darkwiki"
description = ""
version = "0.3.0"
edition = "2021"
authors = ["darkfi <dev@dark.fi>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"
keywords = []
categories = []



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darkfi = {path = "../../", features = ["rpc"]}


# Async
smol = "1.2.5"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.57"
async-channel = "1.6.1"
futures = "0.3.21"

# Misc
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
url = "2.2.2"

# Encoding and parsing
serde = {version = "1.0.142", features = ["derive"]}
serde_json = "1.0.83"
structopt = "0.3.26"





