[package]
name = "pasta"
version = "0.3.0"
authors = ["darkfi <dev@dark.fi>"]
license = "AGPL-3.0-only"
edition = "2018"

[workspace]

[dependencies]
pasta_curves = "0.4.0"
ff = "0.12.0"
group = "0.12.0"
rand = "0.8.5"

[[bin]]
name = "pasta"
path = "main.rs"
