[package]
name = "pasta"
version = "0.3.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2018"

[workspace]

[dependencies]
pasta_curves = "0.4.1"
ff = "0.12.1"
group = "0.12.1"
rand = "0.8.5"

[[bin]]
name = "pasta"
path = "main.rs"
