[package]
name = "pasta"
version = "0.1.0"
authors = ["narodnik <x@x.org>"]
edition = "2018"

[workspace]

[dependencies]
pasta_curves = "0.3.1"
ff = "0.11.0"
group = "0.11.0"
rand = "0.8.5"

[[bin]]
name = "pasta"
path = "main.rs"

