[package]
name = "darkwiki"
description = "CLI utility for interacting with darkwikid"
version = "0.4.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["rpc"]}

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.64"
async-channel = "1.8.0"
futures = "0.3.26"

# Misc
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
url = "2.3.1"

# Encoding and parsing
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
structopt = "0.3.26"
