[package]
name = "darkwiki"
description = "CLI utility for interacting with darkwikid"
version = "0.4.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["rpc"]}

# Async
smol = "1.2.5"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.58"
async-channel = "1.7.1"
futures = "0.3.25"

# Misc
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
url = "2.3.1"

# Encoding and parsing
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
structopt = "0.3.26"
