[package]
name = "darkfid2"
version = "0.4.1"
homepage = "https://dark.fi"
description = "DarkFi node daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../", features = ["async-runtime", "util"]}
darkfi-consensus-contract = {path = "../../src/contract/consensus"}
darkfi-money-contract = {path = "../../src/contract/money"}
darkfi-contract-test-harness = {path = "../../src/contract/test-harness"}
darkfi-sdk = {path = "../../src/sdk"}
darkfi-serial = {path = "../../src/serial"}
log = "0.4.19"
sled = "0.34.7"

# Daemon
async-std = "1.12.0"
easy-parallel = "3.3.0"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.15"
simplelog = "0.12.1"
smol = "1.3.0"

# Argument parsing
serde = {version = "1.0.171", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
