[package]
name = "darkfid2"
version = "0.4.1"
homepage = "https://dark.fi"
description = "DarkFi node daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = "1.12.0"
ctrlc = { version = "3.4.0", features = ["termination"] }
darkfi = {path = "../../", features = ["async-runtime", "util"]}
darkfi-contract-test-harness = {path = "../../src/contract/test-harness"}
easy-parallel = "3.3.0"
log = "0.4.19"
simplelog = "0.12.1"
sled = "0.34.7"
smol = "1.3.0"

# Argument parsing
serde = {version = "1.0.164", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
