[package]
name = "darkirc"
description = "P2P IRC daemon"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../", features = ["event-graph", "rpc", "bs58"]}
darkfi-serial = {path = "../../src/serial"}

# Async
smol = "1.3.0"
futures = "0.3.28"
futures-rustls = "0.24.0"
rustls-pemfile = "1.0.2"
async-std = "1.12.0"
async-trait = "0.1.68"
easy-parallel = "3.3.0"

# Crypto
crypto_box = "0.8.2"
rand = "0.8.5"

# db
sled = "0.34.7"

# Misc
clap = {version = "4.2.7", features = ["derive"]}
log = "0.4.17"
simplelog = "0.12.1"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.15"
url = "2.3.1"
chrono = "0.4.24"
ripemd = "0.1.3"

# Encoding and parsing
serde_json = "1.0.96"
serde = {version = "1.0.162", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
bs58 = "0.4.0"
toml = "0.7.3"
hex = "0.4.3"
