[package]
name = "nodes-tool"
version = "0.1.0"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["blockchain", "node", "wallet"]

[dependencies]

async-std = "1.11.0"
blake3 = "1.3.1"
sled = "0.34.7"

[workspace]
