[package]
name = "nodes-tool"
version = "0.4.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
async-std = "1.12.0"
blake3 = "1.3.3"
darkfi = {path = "../../../", features = ["blockchain", "wallet", "rpc"]}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = {path = "../../../src/serial"}
serde = "1.0.152"
sled = "0.34.7"
