[package]
name = "nodes-tool"
version = "0.3.0"
authors = ["darkfi <dev@dark.fi>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies.darkfi]
path = "../../../"
features = ["blockchain", "node", "wallet"]

[dependencies]
async-std = "1.12.0"
blake3 = "1.3.1"
serde = "1.0.145"
sled = "0.34.7"
