[package]
name = "cashier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darkfi = {path= "../../"}

# Encoding and parsing
serde_json = "1.0.72"
serde = {version = "1.0.130", features = ["derive"]}
hex = "0.4.3"
url = "2.2.2"

# Utilities
clap = { version = "3.0.0", features = ["derive"] }
log = "0.4.14"
simplelog = "0.11.1"
thiserror = "1.0.30"
rand = "0.8.4"
num_cpus = "1.13.0"
lazy_static = "1.4.0"
anyhow = "1.0.49"
num-bigint = {version = "0.4.3", features = ["rand", "serde"]}

# Used for Websockets client implementation.
async-tungstenite = "0.16.0"
tungstenite = "0.16.0"

# Async
async-std = "1.10.0"
async-trait = "0.1.51"
async-channel = "1.6.1"
easy-parallel = "3.1.0"
async-executor = "1.4.1"
futures = "0.3.17"
smol = "1.2.5"
native-tls = "0.2.8"
async-native-tls = "0.4.0"

# Cashier Bitcoin dependencies
bdk = {version = "0.14.0", optional = true}
bitcoin = {version = "0.27.1", optional = true}
secp256k1 = {version = "0.20.3", default-features = false, features = ["rand-std"], optional = true}

# Cashier Ethereum dependencies
hash-db = {version = "0.15.2", optional = true}
keccak-hasher = {version = "0.15.3", optional = true}

# Cashier Solana dependencies
solana-client = {version = "1.8.11", optional = true}
solana-sdk = {version = "1.8.11", optional = true}
spl-associated-token-account = {version = "1.0.3", features = ["no-entrypoint"], optional = true}
spl-token = {version = "3.2.0", features = ["no-entrypoint"], optional = true}

[features]
btc = ["bdk", "bitcoin", "secp256k1"]
eth = ["keccak-hasher", "hash-db"]
sol = ["solana-sdk", "solana-client", "spl-token", "spl-associated-token-account"]
