[package]
name = "tfhe-experiments"
version = "0.4.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
tfhe = {version = "0.1.7", features = ["boolean", "shortint", "x86_64"]}
