[package]
name = "tfhe-experiments"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
tfhe = {version = "0.2.3", features = ["boolean", "shortint", "integer", "x86_64-unix"]}
