[package]
name = "taud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.darkfi]
path = "../../"
features = ["rpc"]

[dependencies]
# Async
smol = "1.2.5"
futures = "0.3.19"
async-std = {version = "1.10.0", features = ["attributes"]}
async-trait = "0.1.52"
async-channel = "1.6.1"
async-executor = "1.4.1"

# Misc
clap = {version = "3.0.7", features = ["derive"]}
log = "0.4.14"
num_cpus = "1.13.1"
simplelog = "0.11.2"
rand = "0.8.5"
chrono = "0.4.19"

# Encoding and parsing
serde_json = "1.0.74"
serde = {version = "1.0.133", features = ["derive"]}
