[package]
name = "taud"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["rpc", "net"]

[dependencies]
# Async
smol = "1.2.5"
futures = "0.3.21"
async-std = {version = "1.11.0", features = ["attributes"]}
async-trait = "0.1.53"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Misc
clap = {version = "3.1.6", features = ["derive"]}
log = "0.4.16"
num_cpus = "1.13.1"
simplelog = "0.12.0-alpha1"
rand = "0.8.5"
chrono = "0.4.19"

# Encoding and parsing
serde_json = "1.0.79"
serde = {version = "1.0.136", features = ["derive"]}
