[package]
name = "validatord"
version = "0.1.0"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["net", "rpc"]

[dependencies]

# Async
smol = "1.2.5"
async-std = "1.10.0"
async-trait = "0.1.52"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Crypto
rand = "0.8.5"

# Structopt dependencies for arguments parsing
serde          = "1.0.104"
serde_json = "1.0.79"
serde_derive   = "1.0.104"
structopt      = "0.3.11"
structopt-toml = "0.5.0"
toml           = "0.5.6"

# Misc
log = "0.4.14"
num_cpus = "1.13.1"
simplelog = "0.11.2"
fxhash = "0.2.1"

[workspace]
