[package]
name = "validatord"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["blockchain", "crypto", "net", "rpc"]

[dependencies]

# Async
smol = "1.2.5"
async-std = "1.11.0"
async-trait = "0.1.53"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Crypto
rand = "0.8.5"
blake3 = "1.3.1"

# Storage
sled = "0.34.7"

# Structopt dependencies for arguments parsing
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
structopt = "0.3.26"
structopt-toml = "0.5.0"
toml = "0.5.9"

# Misc
chrono = "0.4.19"
log = "0.4.16"
num_cpus = "1.13.1"
simplelog = "0.12.0"

[workspace]
