## validatord configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.

# Configuration file to use
config = "validatord_config.toml"

# Accept address
accept = "0.0.0.0:9999"

# Seed nodes
#seeds = "127.0.0.1:9999"

# Manual connections
#connect = "127.0.0.1:9999"

# Connection slots
#slots = 5

# External address
#external = "127.0.0.1:11004"

# Logfile path
#log = "/tmp/darkfid.log"

# The endpoint where validatord will bind its RPC socket
rpc = "127.0.0.1:8000"

# Whether to listen with TLS or plain TCP
serve_tls = false

# Path to DER-formatted PKCS#12 archive. (Unused if serve_tls=false)
# This can be created using openssl:
# openssl pkcs12 -export -out validatord_identity.pfx -inkey key.pem -in cert.pem -certfile validator_certs.pem
tls_identity_path = "~/.config/darkfi/validatord_identity.pfx"

# Password for the created TLS identity. (Unused if serve_tls=false)
tls_identity_password = "FOOBAR"

