[package]
name = "faucetd"
version = "0.3.0"
homepage = "https://dark.fi"
description = "DarkFi faucet daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = "1.12.0"
async-trait = "0.1.57"
blake3 = "1.3.1"
bs58 = "0.4.0"
chrono = "0.4.22"
ctrlc = { version = "3.2.3", features = ["termination"] }
darkfi = {path = "../../", features = ["blockchain", "wallet", "rpc", "net", "node"]}
darkfi-serial = {path = "../../src/serial"}
darkfi-sdk = {path = "../../src/sdk"}
easy-parallel = "3.2.0"
hex = "0.4.3"
lazy-init = "0.5.1"
log = "0.4.17"
rand = "0.8.5"
serde_json = "1.0.85"
simplelog = "0.12.0"
sled = "0.34.7"
smol = "1.2.5"
url = "2.3.1"

# Argument parsing
serde = {version = "1.0.145", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
