## darkfid configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Chain to use (testnet, mainnet)
chain = "testnet"

# Path to the wallet database
wallet_path = "darkfid0/wallet.db"

# Password for the wallet database
wallet_pass = "changeme"

# Path to the blockchain database directory
database = "darkfid0/blockchain"

# JSON-RPC listen url
rpc_listen = "tcp://127.0.0.1:8340"

# Participate in the consensus protocol
consensus = true

# Enable single-node mode for local testing
single_node = true

# P2P accept addresses for the consensus protocol
consensus_p2p_accept = ["tcp://127.0.0.1:8341"]

# P2P external addresses for the consensus protocol
consensus_p2p_external = ["tcp://127.0.0.1:8341"]

# Connection slots for the consensus protocol
#consensus_slots = 8

# Connection slots for the consensus protocol
#consensus_p2p_seed = []

# Peers to connect to for the consensus protocol
#consensus_p2p_peer = []


# Prefered transports of outbound connections for the consensus protocol
consensus_p2p_transports = ["tls", "tcp"]

# P2P accept addresses for the syncing protocol
sync_p2p_accept = ["tcp://127.0.0.1:8342"]

# P2P external addresses for the syncing protocol
sync_p2p_external = ["tcp://127.0.0.1:8342"]

# Connection slots for the syncing protocol
#sync_slots = 8

# Seed nodes to connect to for the syncing protocol
#sync_p2p_seed = []

# Peers to connect to for the syncing protocol
#sync_p2p_peer = []

# Prefered transports of outbound connections for the syncing protocol
sync_p2p_transports = ["tls", "tcp"]

# Enable localnet hosts
localnet = true

# Enable channel log
channel_log = true

# Whitelisted faucet public key
faucet_pub = ["DqaZzCTipXeJw4kcc6ro1SJuzo3diaNjFiaAnKTGQEK1"]

# Verify system clock is correct
#clock_sync = true
