[package]
name = "dnetview"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["rpc"]

[dependencies]
# Tui
termion = "1.5.6"
tui = {version = "0.17.0", features = ["termion"]}

# Async
smol = "1.2.5"
async-std = {version = "1.11.0", features = ["attributes"]}
easy-parallel = "3.2.0"
async-channel = "1.6.1"

# Misc
clap = "3.1.6"
rand = "0.8.5"
simplelog = "0.11.2"
log = "0.4.14"
num_cpus = "1.13.1"
url = "2.2.2"
fxhash = "0.2.1"

# Encoding and parsing
serde_json = "1.0.79"
serde = {version = "1.0.136", features = ["derive"]}
