## map configuration file
##
## Please make sure you go through all the settings so you can configure
## map properly.

[[nodes]]
name = "Node 1"
rpc_url = "tcp://127.0.0.1:8000"
node_type = "NORMAL"

[[nodes]]
name = "Node 2"
rpc_url = "tcp://127.0.0.1:7777"
node_type = "NORMAL"

[[nodes]]
name = "Node 3"
rpc_url = "tcp://127.0.0.1:1234"
node_type = "NORMAL"

# Darkfid node can run both sync and consensus p2p networks,
# so we need to create a record for each network.
#[[nodes]]
#name = "darkfid-sync"
#rpc_url = "tcp://127.0.0.1:8340"
#node_type = "NORMAL"

#[[nodes]]
#name = "darkfid-consensus"
#rpc_url = "tcp://127.0.0.1:8340"
#node_type = "CONSENSUS"
