[package]
name = "pow"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
randomx = {git = "https://github.com/darkrenaissance/RandomX"}
darkfi-serial = {path = "../../../src/serial"}
darkfi-sdk = {path = "../../../src/sdk", features = ["async"]}
darkfi = {path = "../../../", features = ["util"]}

blake2b_simd = "1.0.1"
rand = "0.8.5"
