[package]
name = "taud"
description = "Encrypted tasks management app using peer-to-peer network and raft consensus."
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = { path = "../../../", features = ["rpc", "raft", "net", "bs58"]}
darkfi-serial = { path = "../../../src/serial" }

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.64"
easy-parallel = "3.2.0"
futures = "0.3.26"

# Misc
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
chrono = "0.4.23"
thiserror = "1.0.38"
ctrlc = { version = "3.2.4", features = ["termination"] }
url = "2.3.1"

# Encoding and parsing
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
structopt = "0.3.26"
structopt-toml = "0.5.1"
crypto_box = {version = "0.8.2", features = ["std"]}
hex = "0.4.3"
bs58 = "0.4.0"
toml = "0.7.1"
