[package]
name = "taud"
description = "Encrypted tasks management app using peer-to-peer network and Event Graph."
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[lib]
name = "taud"
path = "src/lib.rs"

[[bin]]
name = "taud"
path = "src/main.rs"

[dependencies]
darkfi = { path = "../../../", features = [
    "bs58",
    "async-daemonize",
    "event-graph",
    "rpc",
] }
darkfi-serial = { path = "../../../src/serial" }

# Event Graph DB
sled = "0.34.7"

# Crypto
blake3 = "1.5.1"
crypto_box = { version = "0.9.1", features = ["std", "chacha20"] }
rand = "0.8.5"

# Encoding and parsing
bs58 = "0.5.1"
hex = "0.4.3"
toml = "0.8.14"

# Misc
async-trait = "0.1.80"
chrono = "0.4.38"
futures = "0.3.30"
libc = "0.2.155"
log = "0.4.21"
thiserror = "1.0.61"
tinyjson = "2.5.1"
url = "2.5.0"

# Daemon
easy-parallel = "3.3.1"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.17"
simplelog = "0.12.2"
smol = "2.0.0"

# Argument parsing
serde = { version = "1.0.203", features = ["derive"] }
structopt = "0.3.26"
structopt-toml = "0.5.1"
