[package]
name = "taud"
description = "Encrypted tasks management app using peer-to-peer network and raft consensus."
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = { path = "../../../", features = ["event-graph", "rpc", "bs58"]}
darkfi-serial = { path = "../../../src/serial" }

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.68"
easy-parallel = "3.3.0"
futures = "0.3.28"

# Misc
libc = "0.2.144"
log = "0.4.18"
simplelog = "0.12.1"
rand = "0.8.5"
chrono = "0.4.26"
thiserror = "1.0.40"
ctrlc = { version = "3.4.0", features = ["termination"] }
url = "2.4.0"

# Encoding and parsing
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
structopt = "0.3.26"
structopt-toml = "0.5.1"
crypto_box = {version = "0.8.2", features = ["std"]}
hex = "0.4.3"
bs58 = "0.5.0"
toml = "0.7.4"
