[package]
name = "taud"
version = "0.3.0"
edition = "2021"


[dependencies]

darkfi = { path = "../../../", features = ["rpc", "raft", "net"]}

# Async
smol = "1.2.5"
async-std = {version = "1.11.0", features = ["attributes"]}
async-trait = "0.1.53"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"
futures = "0.3.21"

# Misc
clap = {version = "3.1.12", features = ["derive"]}
log = "0.4.16"
num_cpus = "1.13.1"
simplelog = "0.12.0"
rand = "0.8.5"
chrono = "0.4.19"
thiserror = "1.0.30"
ctrlc-async = {version= "3.2.2", default-features = false, features = ["async-std", "termination"]}

# Encoding and parsing
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
structopt = "0.3.26"
structopt-toml = "0.5.0"
crypto_box = {version = "0.7.2", features = ["std"]}
hex = "0.4.3"
