[package]
name = "plonkbyhand"
version = "0.3.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
halo2 = { path = "/opt/halo2" }

[patch.crates-io]
halo2 =  {git = "https://github.com/zcash/halo2", branch = "main"}
