# darkfi-mmproxy daemon listen URL
#listen = "http://127.0.0.1:3333"

[monerod]
# Monero network to use (mainnet/testnet)
network = "mainnet"

# monerod RPC address
rpc = "http://127.0.0.1:18081/json_rpc"
