[package]
name = "darkfi-derive"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Crate for serialization derive macros"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.3.0"
proc-macro2 = "1.0.50"
syn = {version = "1.0.107", features = ["full", "fold"]}

darkfi-derive-internal = {version = "0.3.0", path = "../derive-internal"}
