[package]
name = "darkfi-derive"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Crate for serialization derive macros"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.0.0"
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = {version = "2.0.66", features = ["full", "fold"]}

darkfi-derive-internal = {version = "0.4.1", path = "../derive-internal"}

[features]
default = []
async = ["darkfi-derive-internal/async"]

[lints]
workspace = true

