[book]
authors = ["DarkFi"]
language = "en"
multilingual = false
src = "src"
title = "The DarkFi Book"

[output.html]
theme = "ayu"
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.katex]

[preprocessor.katex]
