name: CI Checks

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential clang libclang-dev llvm-dev libudev-dev pkg-config

      - name: Run tests
        run: |
          make test

  feature-powerset:
    name: Test crate feature powerset on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@cargo-hack

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential clang libclang-dev llvm-dev libudev-dev pkg-config

      - name: Run feature powerset builds
        run: |
          make check

  fmt:
    name: rustfmt
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: |
          rustup component add rustfmt
          cargo fmt -- --check


