name: Build and Test

on:
    push:
        branches:
            - master
        pull_request:

jobs:
    compile-and-test:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
                components: rustfmt, clippy
            - name: Install sqlcipher
              run: |
                sudo apt-get update
                sudo apt-get install libsqlcipher-dev
            - name: Create Config Dir 
              run: |
                mkdir -p ~/.config/darkfi
            - name: Compile
              run: |
                cargo build --features sol --release
                cargo test
