name: Build and Test

on:
    push:
        branches:
            - master
        pull_request:

jobs:
    compile-and-test:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
                components: rustfmt, clippy
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install libudev-dev
            - name: Create config directory
              run: |
                mkdir -p ~/.config/darkfi
            - name: Test with all features
              run: |
                cargo test --release --all-features
